k9s:
  cluster: api-cluster0017-non-prod-ichp-ing-net:6443
  namespace:
    active: foundatio-dev
    lockFavorites: false
    favorites:
    - foundatio-dev
    - default
  view:
    active: secrets
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
